QCC=fteqcc

all:
	mkdir -pv ../../progs/
	$(QCC) $(CFLAGS) -I../../../src/server counterstrike.qc
	$(QCC) $(CFLAGS) -I../../../src/server deathmatch.qc
	$(QCC) $(CFLAGS) -I../../../src/server zombie.qc
