/*
 * Copyright (c) 2016-2021 Marco Cawthorne <marco@icculus.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
 * IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
 * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

enum
{
	CSANIM_DUMMY1,
	CSANIM_IDLE,
	CSANIM_IDLE_CROUCH,
	CSANIM_WALK,
	CSANIM_RUN,
	CSANIM_RUN_CROUCH,
	CSANIM_JUMP,
	CSANIM_LONGJUMP,
	CSANIM_SWIM,
	CSANIM_TREADWATER,
	CSANIM_CROUCH_AIM_CARBINE,
	CSANIM_CROUCH_SHOOT_CARBINE,
	CSANIM_CROUCH_RELOAD_CARBINE,
	CSANIM_AIM_CARBINE,
	CSANIM_SHOOT_CARBINE,
	CSANIM_RELOAD_CARBINE,
	CSANIM_CROUCH_AIM_ONEHAND,
	CSANIM_CROUCH_SHOOT_ONEHAND,
	CSANIM_CROUCH_RELOAD_ONEHAND,
	CSANIM_AIM_ONEHAND,
	CSANIM_SHOOT_ONEHAND,
	CSANIM_RELOAD_ONEHAND,
	CSANIM_CROUCH_AIM_DUALPISTOLS,
	CSANIM_CROUCH_SHOOT_DUALPISTOLS,
	CSANIM_CROUCH_SHOOT2_DUALPISTOLS,
	CSANIM_CROUCH_RELOAD_DUALPISTOLS,
	CSANIM_AIM_DUALPISTOLS,
	CSANIM_SHOOT_DUALPISTOLS,
	CSANIM_SHOOT2_DUALPISTOLS,
	CSANIM_RELOAD_DUALPISTOLS,
	CSANIM_CROUCH_AIM_RIFLE,
	CSANIM_CROUCH_SHOOT_RIFLE,
	CSANIM_CROUCH_RELOAD_RIFLE,
	CSANIM_AIM_RIFLE,
	CSANIM_SHOOT_RIFLE,
	CSANIM_RELOAD_RIFLE,
	CSANIM_CROUCH_AIM_MP5,
	CSANIM_CROUCH_SHOOT_MP5,
	CSANIM_CROUCH_RELOAD_MP5,
	CSANIM_AIM_MP5,
	CSANIM_SHOOT_MP5,
	CSANIM_RELOAD_MP5,
	CSANIM_CROUCH_AIM_SHOTGUN,
	CSANIM_CROUCH_SHOOT_SHOTGUN,
	CSANIM_CROUCH_RELOAD_SHOTGUN,
	CSANIM_AIM_SHOTGUN,
	CSANIM_SHOOT_SHOTGUN,
	CSANIM_RELOAD_SHOTGUN,
	CSANIM_CROUCH_AIM_PARA,
	CSANIM_CROUCH_SHOOT_PARA,
	CSANIM_CROUCH_RELOAD_PARA,
	CSANIM_AIM_PARA,
	CSANIM_SHOOT_PARA,
	CSANIM_RELOAD_PARA,
	CSANIM_DUMMY2,
	CSANIM_DUMMY3,
	CSANIM_AIM_GRENADE,
	CSANIM_SHOOT_GRENADE,
	CSANIM_CROUCH_AIM_GRENADE,
	CSANIM_CROUCH_SHOOT_GRENADE,
	CSANIM_CROUCH_AIM_C4,
	CSANIM_CROUCH_SHOOT_C4,
	CSANIM_AIM_C4,
	CSANIM_SHOOT_C4,
	CSANIM_RELOAD_C4,
	CSANIM_DUPLICATE1,
	CSANIM_DUPLICATE2,
	CSANIM_DUPLICATE3,
	CSANIM_DUPLICATE4,
	CSANIM_DUPLICATE5,
	CSANIM_DUPLICATE6,
	CSANIM_DUPLICATE7,
	CSANIM_DUPLICATE8,
	CSANIM_CROUCH_AIM_KNIFE,
	CSANIM_CROUCH_SHOOT_KNIFE,
	CSANIM_AIM_KNIFE,
	CSANIM_SHOOT_KNIFE,
	CSANIM_CROUCH_AIM_AK47,
	CSANIM_CROUCH_SHOOT_AK47,
	CSANIM_CROUCH_RELOAD_AK47,
	CSANIM_AIM_AK47,
	CSANIM_SHOOT_AK47,
	CSANIM_RELOAD_AK47,
	CSANIM_GUT_FLINCH,
	CSANIM_HEAD_FLINCH,
	CSANIM_DEATH1,	/* land on stomach */
	CSANIM_DEATH2,	/* land on back */
	CSANIM_DEATH3,	/* dramatic death */
	CSANIM_DIE_HEAD,
	CSANIM_DIE_GUT,
	CSANIM_DIE_LEFT,
	CSANIM_DIE_BACK,
	CSANIM_DIE_RIGHT,
	CSANIM_DIE_FORWARD,
	CSANIM_CROUCH_DIE
};

